version: "3"
services:
  mongo:
    image: mongo
    hostname: "mongo"
  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
  app:
    image: ${IMG_NAME}
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=${NODE_ENV}
      - LOG_LEVEL=${LOG_LEVEL}
      - MONGO_URI=${MONGO_URI}
    links:
      - mongo
      - rabbit
    depends_on:
      - mongo
      - rabbit
    command: bash -c "/wait && yarn test"
