FROM node:latest

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json /usr/src/app/

RUN yarn install
RUN npm i -g cross-env jest-teamcity-reporter

COPY . /usr/src/app


RUN yarn start

ARG REST_PORT
EXPOSE ${REST_PORT}:${REST_PORT}
